version: '3'

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.6
    env_file:
      - .env
    environment:
      # http_proxy:
      # https_proxy:       
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      # MEILI_NO_ANALYTICS: ${MEILI_NO_ANALYTICS:-true}
      # MEILI_ENV: ${MEILI_ENV:-development}
      # MEILI_LOG_LEVEL:
      MEILI_DB_PATH: ${MEILI_DB_PATH}
    ports:
      - ${MEILI_PORT:-7700}:7700
    volumes:
      - meilisearch:/meili_data
    restart: unless-stopped

volumes:
  meilisearch: